version: "3"
services:
  app:
    container_name: app_bolt
    build: ./.docker/bolt
    working_dir: /app
    volumes:
      - .:/app
    tty: true
    env_file: .env
    command:  >
      sh -c "npm install && npm run build"